app_homepage:
    path: /
    controller: App\Controller\PagesController::home

app_simulator:
    path: /simulateur
    controller: App\Controller\SimulatorController::index

app_request:
    path: /demande-de-prêt
    controller: App\Controller\DemandeCreditController::index

app_about:
    path: /a-propos
    controller: App\Controller\PagesController::about

app_contact:
    path: /contact
    controller: App\Controller\ContactController::contact

show_credit:
    path:     /ajax_request
    controller: App\Controller\SimulatorController::showMensualites
    methods: POST

credit_index:
    path: /admin/credit
    controller: App\Controller\CreditController::index
    methods: GET

credit_new:
    path: /admin/credit/new
    controller: App\Controller\CreditController::new
    methods: GET|POST

credit_show:
    path: /admin/credit/{id}
    controller: App\Controller\CreditController::show
    methods: GET

credit_edit:
    path: /admin/credit/{id}/edit
    controller: App\Controller\CreditController::edit
    methods: GET|POST

credit_delete:
    path: /admin/credit/{id}
    controller: App\Controller\CreditController::delete
    methods: POST

duree_index:
    path: /admin/duree
    controller: App\Controller\DureeController::index
    methods: GET

duree_new:
    path: /admin/duree/new
    controller: App\Controller\DureeController::new
    methods: GET|POST

duree_show:
    path: /admin/duree/{id}
    controller: App\Controller\DureeController::show
    methods: GET

duree_edit:
    path: /admin/duree/{id}/edit
    controller: App\Controller\DureeController::edit
    methods: GET|POST

duree_delete:
    path: /admin/duree/{id}
    controller: App\Controller\DureeController::delete
    methods: POST

app_login:
    path: /log-mon-credit-europeen
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

#app_register:
#    path: /register
#    controller: App\Controller\RegistrationController::register

